/**
 * ProSalonPOS — .exe Build Script
 * 
 * Orchestrates the full production build:
 * 
 *   1. Build the frontend (npm run build in prosalonpos-station)
 *   2. Copy built frontend into server's public/ folder
 *   3. Switch Prisma to SQLite and create the database
 *   4. Bundle Node.js runtime + server + frontend into a folder
 *   5. Create an Inno Setup script for the Windows installer
 * 
 * Prerequisites:
 *   - prosalonpos-station folder must exist alongside prosalonpos-server
 *   - Node.js installed
 *   - Inno Setup installed (for final .exe creation — optional, can be done manually)
 * 
 * Usage:  node scripts/build-exe.js
 * 
 * Output: dist/ folder containing everything needed for the installer
 */
import { execSync } from 'child_process';
import { existsSync, mkdirSync, cpSync, writeFileSync, rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

var __dirname = dirname(fileURLToPath(import.meta.url));
var serverRoot = join(__dirname, '..');
var stationRoot = join(serverRoot, '..', 'prosalonpos-station');
var distDir = join(serverRoot, 'dist');
var distServer = join(distDir, 'server');
var distPublic = join(distServer, 'public');

console.log('');
console.log('  ╔══════════════════════════════════════════╗');
console.log('  ║   ProSalonPOS — .exe Build Script        ║');
console.log('  ╚══════════════════════════════════════════╝');
console.log('');

// ════════════════════════════════════════════
// STEP 1: Verify prerequisites
// ════════════════════════════════════════════

console.log('[1/6] Checking prerequisites...');

if (!existsSync(stationRoot)) {
  console.error('[ERROR] prosalonpos-station folder not found at: ' + stationRoot);
  console.error('        The station folder must be in the same parent directory as prosalonpos-server.');
  process.exit(1);
}

if (!existsSync(join(stationRoot, 'package.json'))) {
  console.error('[ERROR] No package.json found in prosalonpos-station.');
  process.exit(1);
}

console.log('  ✅ Station folder found');
console.log('  ✅ Server folder found');

// ════════════════════════════════════════════
// STEP 2: Build the frontend
// ════════════════════════════════════════════

console.log('');
console.log('[2/6] Building frontend (npm run build)...');

try {
  execSync('npm run build', { cwd: stationRoot, stdio: 'inherit' });
  console.log('  ✅ Frontend built successfully');
} catch (err) {
  console.error('[ERROR] Frontend build failed. Fix build errors first.');
  process.exit(1);
}

// ════════════════════════════════════════════
// STEP 3: Prepare dist folder
// ════════════════════════════════════════════

console.log('');
console.log('[3/6] Preparing dist folder...');

// Clean previous build
if (existsSync(distDir)) {
  rmSync(distDir, { recursive: true, force: true });
}
mkdirSync(distDir, { recursive: true });
mkdirSync(distServer, { recursive: true });

// Copy server source files (not node_modules)
var serverFiles = ['src', 'prisma', 'scripts', 'package.json', 'package-lock.json'];
serverFiles.forEach(function(file) {
  var srcPath = join(serverRoot, file);
  var destPath = join(distServer, file);
  if (existsSync(srcPath)) {
    cpSync(srcPath, destPath, { recursive: true });
  }
});

// Copy built frontend into server's public/ folder
var stationDist = join(stationRoot, 'dist');
if (!existsSync(stationDist)) {
  console.error('[ERROR] Frontend build output not found at: ' + stationDist);
  process.exit(1);
}
cpSync(stationDist, distPublic, { recursive: true });

console.log('  ✅ Server files copied');
console.log('  ✅ Frontend build copied to server/public/');

// ════════════════════════════════════════════
// STEP 4: Create production .env
// ════════════════════════════════════════════

console.log('');
console.log('[4/6] Creating production .env...');

var jwtSecret = 'prosalonpos-' + Date.now() + '-' + Math.random().toString(36).substring(2, 15);

var envContent = [
  '# ProSalonPOS Production Environment',
  '# Auto-generated by build-exe.js',
  '',
  'PORT=3002',
  'DATABASE_URL=file:C:\\ProgramData\\ProSalonPOS\\prosalonpos.db',
  'NODE_ENV=production',
  'JWT_SECRET=' + jwtSecret,
  ''
].join('\n');

writeFileSync(join(distServer, '.env'), envContent);
console.log('  ✅ Production .env created (port 3002, SQLite mode)');

// ════════════════════════════════════════════
// STEP 5: Install production dependencies & generate SQLite
// ════════════════════════════════════════════

console.log('');
console.log('[5/6] Installing dependencies and creating SQLite database...');

// Create ProgramData directory for the database (writable by all users)
var programDataDir = 'C:\\ProgramData\\ProSalonPOS';
if (!existsSync(programDataDir)) {
  mkdirSync(programDataDir, { recursive: true });
  console.log('  ✅ Created ' + programDataDir);
}

try {
  // Install production deps only
  execSync('npm install --omit=dev', { cwd: distServer, stdio: 'inherit' });

  // Install prisma as dev dep for generation
  execSync('npm install prisma --save-dev', { cwd: distServer, stdio: 'inherit' });

  // Switch schema to SQLite
  var schemaPath = join(distServer, 'prisma', 'schema.prisma');
  var sqliteSchemaPath = join(distServer, 'prisma', 'schema.sqlite.prisma');
  if (existsSync(sqliteSchemaPath)) {
    cpSync(sqliteSchemaPath, schemaPath);
  }

  // Generate Prisma client for SQLite
  execSync('npx prisma generate', { cwd: distServer, stdio: 'inherit' });

  // Create the SQLite database at the ProgramData location (writable)
  execSync('npx prisma db push --accept-data-loss', { cwd: distServer, stdio: 'inherit' });

  // Copy the database into dist/server/prisma/ so Inno Setup can bundle it
  var dbSource = join(programDataDir, 'prosalonpos.db');
  var dbDest = join(distServer, 'prisma', 'prosalonpos.db');
  if (existsSync(dbSource)) {
    cpSync(dbSource, dbDest);
    console.log('  ✅ Database copied into dist for Inno Setup bundling');
  }

  console.log('  ✅ Dependencies installed');
  console.log('  ✅ SQLite database created at ' + programDataDir);
} catch (err) {
  console.error('[ERROR] Failed to set up production build:', err.message);
  process.exit(1);
}

// ════════════════════════════════════════════
// STEP 6: Generate Inno Setup script
// ════════════════════════════════════════════

console.log('');
console.log('[6/6] Generating Inno Setup script...');

var innoScript = [
  '; ProSalonPOS Installer Script',
  '; Generated by build-exe.js',
  '; Compile this with Inno Setup to create ProSalonPOS-Setup.exe',
  '',
  '[Setup]',
  'AppName=ProSalonPOS',
  'AppVersion=1.0.0',
  'AppPublisher=ProSalonPOS',
  'DefaultDirName={autopf}\\ProSalonPOS',
  'DefaultGroupName=ProSalonPOS',
  'OutputDir=.',
  'OutputBaseFilename=ProSalonPOS-Setup',
  'Compression=lzma2',
  'SolidCompression=yes',
  'PrivilegesRequired=admin',
  '',
  '[Dirs]',
  '; Create ProgramData folder for database + license (writable by all users)',
  'Name: "{commonappdata}\\ProSalonPOS"; Permissions: users-full',
  '',
  '[Files]',
  '; Bundle the entire server folder (includes frontend, prisma, node_modules)',
  'Source: "server\\*"; DestDir: "{app}\\server"; Flags: ignoreversion recursesubdirs',
  '',
  '; Bundle Node.js runtime',
  'Source: "node\\*"; DestDir: "{app}\\node"; Flags: ignoreversion recursesubdirs',
  '',
  '; Copy the empty database to ProgramData (skip if already exists — keeps data on upgrade)',
  'Source: "server\\prisma\\prosalonpos.db"; DestDir: "{commonappdata}\\ProSalonPOS"; Flags: onlyifdoesntexist',
  '',
  '[Icons]',
  '; Desktop shortcut opens browser to the app',
  'Name: "{commondesktop}\\ProSalonPOS"; Filename: "http://localhost:3002"',
  '; Start menu shortcut',
  'Name: "{group}\\ProSalonPOS"; Filename: "http://localhost:3002"',
  '; Start menu — Start Server (hidden, auto-runs on boot)',
  'Name: "{userstartup}\\ProSalonPOS Server"; Filename: "{app}\\node\\node.exe"; Parameters: "src/server.js"; WorkingDir: "{app}\\server"; IconFilename: "{app}\\node\\node.exe"',
  '',
  '[Run]',
  '; Start the server immediately after installation (hidden window)',
  'Filename: "{app}\\node\\node.exe"; Parameters: "src/server.js"; WorkingDir: "{app}\\server"; Flags: runhidden nowait',
  '',
  '; Wait a moment for server to start, then open browser',
  'Filename: "{cmd}"; Parameters: "/c timeout /t 3 /nobreak >nul && start http://localhost:3002"; Flags: runhidden nowait',
  '',
  '[UninstallDelete]',
  '; Clean up startup shortcut on uninstall',
  'Type: files; Name: "{userstartup}\\ProSalonPOS Server.lnk"',
  '; Clean up ProgramData on full uninstall',
  'Type: filesandordirs; Name: "{commonappdata}\\ProSalonPOS"',
  ''
].join('\n');

writeFileSync(join(distDir, 'ProSalonPOS.iss'), innoScript);

console.log('  ✅ Inno Setup script created at: dist/ProSalonPOS.iss');

// ════════════════════════════════════════════
// DONE
// ════════════════════════════════════════════

console.log('');
console.log('  ══════════════════════════════════════════');
console.log('  ✅ Build complete!');
console.log('');
console.log('  Next steps:');
console.log('  1. Download Node.js portable into dist/node/');
console.log('     (https://nodejs.org/dist/v20.x.x/node-v20.x.x-win-x64.zip)');
console.log('  2. Add an icon.ico file to dist/');
console.log('  3. Install Inno Setup (https://jrsoftware.org/isinfo.php)');
console.log('  4. Open dist/ProSalonPOS.iss in Inno Setup and compile');
console.log('  5. The installer will be created as dist/ProSalonPOS-Setup.exe');
console.log('  ══════════════════════════════════════════');
console.log('');
